apiVersion: v1
kind: Namespace
metadata:
  name: boutique
  labels:
    cost-center: cc-1234
    env: lab
---
# ╔═══════════════════════════════════════════════════════════════╗
# ║ Frontend — bien dimensionné                                   ║
# ╚═══════════════════════════════════════════════════════════════╝
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: { app: frontend, team: frontend }
spec:
  replicas: 2
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend, team: frontend, env: lab }
    spec:
      containers:
        - name: frontend
          image: ghcr.io/stefanprodan/podinfo:6.7.0
          ports: [{ containerPort: 9898 }]
          resources:
            requests: { cpu: "100m", memory: "64Mi" }
            limits:   { cpu: "300m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: frontend, labels: { app: frontend } }
spec:
  selector: { app: frontend }
  ports: [{ port: 80, targetPort: 9898 }]
